### PR TITLE
Add swipe gesture for guitable and scroll container

### PR DESCRIPTION
**Pull request by deveee**
Needs https://github.com/MoNTE48/Irrlicht/pull/15

### CODE REVIEW

**Comment by MoNTE48** [comment]
@deveee, think about how to fix Actions, please.

**Comment by MoNTE48** [comment]
It didn't help... @deveee

**Comment by deveee** [comment]
It seems that something is messed, I will look later
```
2024-01-02T08:54:35.3721096Z /home/runner/work/MultiCraft/MultiCraft/src/gui/guiScrollContainer.cpp:34:2: error: #else after #else
2024-01-02T08:54:35.3722633Z #else
2024-01-02T08:54:35.3723131Z  ^
2024-01-02T08:54:35.3725495Z /home/runner/work/MultiCraft/MultiCraft/src/gui/guiScrollContainer.cpp:22:2: error: unterminated conditional directive
2024-01-02T08:54:35.3728210Z #ifdef _IRR_COMPILE_WITH_SDL_DEVICE_
2024-01-02T08:54:35.3729225Z  ^
2024-01-02T08:54:35.3731052Z /home/runner/work/MultiCraft/MultiCraft/src/gui/guiScrollContainer.cpp:139:2: error: expected '{' or ','
2024-01-02T08:54:35.3732773Z }
2024-01-02T08:54:35.3733373Z  ^
2024-01-02T08:54:35.3868498Z [ 42%] Building CXX object src/CMakeFiles/multicraftserver.dir/script/lua_api/l_util.cpp.o
2024-01-02T08:54:35.4323226Z 3 errors generated.
2024-01-02T08:54:35.4385698Z make[2]: *** [src/CMakeFiles/multicraft.dir/build.make:1098: src/CMakeFiles/multicraft.dir/gui/guiScrollContainer.cpp.o] Error 1
2024-01-02T08:54:35.4388794Z make[1]: *** [CMakeFiles/Makefile2:575: src/CMakeFiles/multicraft.dir/all] Error 2
2024-01-02T08:54:35.4390063Z make[1]: *** Waiting for unfinished jobs....
```

**Comment by deveee** [comment]
Android needs updated irrlicht headers

**Pull request merged**
