### PR TITLE
Port drawtype colordegrotate and 4dir from upstream

### PR DESCRIPTION
**Pull request by Emojigit**
This PR ports minetest/minetest#7840 and minetest/minetest#11431 into MultiCraft.

## To do

This PR is Ready for Review.

## How to test

Use the nodes coming with devtest.

You can also load mods that use these drawtypes. Here is a photo showing nodes using 4dir: (Modified [Advtrains Screen Doors](https://content.minetest.net/packages/Emojiminetest/advtrains_doors/) that uses 4dir instead of facedir)

screenshot_20240715_185657

### CODE REVIEW

**Comment by Emojigit** [comment]
The protocol used by MultiCraft clients is compatible with Minetest servers. However, without porting these changes, some nodes may behave weirdly (in this case, not being able to rotate or colorize as intended).

**Comment by MoNTE48** [comment]
> The protocol used by MultiCraft clients is compatible with Minetest servers. However, without porting these changes, some nodes may behave weirdly (in this case, not being able to rotate or colorize as intended).

We are committed to developing our own games and servers.
A compatible protocol is more of a side effect and compatibility can be broken at any time.

**Comment by Emojigit** [comment]
> A compatible protocol is more of a side effect and compatibility can be broken at any time.

Oh, that's sad to hear. MultiCraft is currently the most popular if not the only Minetest-compatible client on the damn closed iOS App Store, serving as the dominant way for people new to Minetest to join servers (according to observations on my server). By the way, I wonder why MultiCraft is legal on the App Store while the upstream is not...

**Comment by Emojigit** [comment]
Closing this PR as won't fix. (Discussions may continue)

**Pull request closed without merging**
